// <auto-generated />
using System;
using Blog.infrastructure.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Blog.infrastructure.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Blog.infrastructure.Model.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Auther");

                    b.Property<string>("Context");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Auther = "admin",
                            Context = "This is my first Article",
                            Date = new DateTime(2019, 4, 23, 17, 41, 46, 490, DateTimeKind.Local).AddTicks(756),
                            Title = "First Welcome Article"
                        },
                        new
                        {
                            Id = 2,
                            Auther = "管理员",
                            Context = "这是我的第二篇博客",
                            Date = new DateTime(2019, 4, 23, 17, 41, 46, 490, DateTimeKind.Local).AddTicks(8532),
                            Title = "第二个博客"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
